/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PacienteRouteImport } from './routes/paciente'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as IndexRouteImport } from './routes/index'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteRoute = PacienteRouteImport.update({
  id: '/paciente',
  path: '/paciente',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/agenda': typeof AgendaRoute
  '/aulas': typeof AulasRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/paciente': typeof PacienteRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/agenda': typeof AgendaRoute
  '/aulas': typeof AulasRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/paciente': typeof PacienteRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/agenda': typeof AgendaRoute
  '/aulas': typeof AulasRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/notificacoes': typeof NotificacoesRoute
  '/paciente': typeof PacienteRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/agenda'
    | '/aulas'
    | '/dashboard'
    | '/historico'
    | '/notificacoes'
    | '/paciente'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/agenda'
    | '/aulas'
    | '/dashboard'
    | '/historico'
    | '/notificacoes'
    | '/paciente'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/acesso'
    | '/agenda'
    | '/aulas'
    | '/dashboard'
    | '/historico'
    | '/notificacoes'
    | '/paciente'
    | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoRoute: typeof AcessoRoute
  AgendaRoute: typeof AgendaRoute
  AulasRoute: typeof AulasRoute
  DashboardRoute: typeof DashboardRoute
  HistoricoRoute: typeof HistoricoRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PacienteRoute: typeof PacienteRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente': {
      id: '/paciente'
      path: '/paciente'
      fullPath: '/paciente'
      preLoaderRoute: typeof PacienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoRoute: AcessoRoute,
  AgendaRoute: AgendaRoute,
  AulasRoute: AulasRoute,
  DashboardRoute: DashboardRoute,
  HistoricoRoute: HistoricoRoute,
  NotificacoesRoute: NotificacoesRoute,
  PacienteRoute: PacienteRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
